### ISSUE TITLE
IxiaSモデル・テーブル定義・リポジトリはapp/lib/配下に置いてください

### ISSUE THREAD

**Issue by knts0** [s10a137g/todo-app#1]
すいません。初見だとわからないとこだとは思うのですが
- app/modelにあるIxiaSのモデル -> app/lib/modelへ
- app/persistence -> app/lib/persistenceへ

配置お願いいたしますｍｍ

app/model以下はView Modelを置きます。
app/persistenceはなくてOkです

**Comment by knts0** [comment]
ディレクトリの切り方の考え方として

Play FrameworkがMVCを採用しているので、それに絡んだものはmodel, views, controllersに配置

それ以外のモデルやDBレイヤーのものをlib以下に配置

という感じです。

**Comment by s10a137g** [comment]
修正しました。
