### ISSUE TITLE
View Modelの設計

### ISSUE THREAD

**Issue by knts0** [s10a137g/todo-app#2]
https://github.com/s10a137g/todo-app/issues/1
に付随して、app/model配下のView Modelの設計をお願いします。
現状、ViewValueHomeをいろいろな箇所で使っていますが、
ViewValueCommonを継承して、各ページごとに定義をお願いします。

**Comment by knts0** [comment]
```
        views.html.category
          .list(defaultVv.copy(title = "Category List"), categoryList)
```

defaultVv.copy(title = "Category List")
でインスタンスの中身を書き換えてると思いますが、View Modelの役割としては「viewに沿った形でデータをControllerから渡す」なので、

一つのdefaultVvを使い回すというよりは、各view（ページ）、例えばTodo追加画面とか編集画面ごとに定義するイメージです！

**Comment by s10a137g** [comment]
修正しました。
