### ISSUE TITLE
EmbeddedId型からidを取り出す際の処理の修正

### ISSUE THREAD

**Issue by knts0** [s10a137g/todo-app#3]
EmbeddedId型はその名の通りIdの埋め込まれた型なので、Optionでない形でIdを取り出すことができるのが強みです。

例えば

https://github.com/s10a137g/todo-app/blob/main/app/controllers/category/CategoryController.scala#L139

```
updateCategory.v.id.get.toString,
```

などは、

```
updateCategory.id.toString,
```

にしましょう。

**Comment by knts0** [comment]
また、Optionに対して`.get`するのは基本的には（条件分岐等で確実に値が入ることが保証される場合以外は）NGです。
Noneだった場合に例外になってしまい、適切な例外処理でキャッチしていないとアプリケーションが落ちてしまうためです。
必ずOptionの場合はパターンマッチなどして値を取り出すようにしてくださいｍｍ

**Comment by s10a137g** [comment]
修正しました。
