### ISSUE TITLE
name値のスペース

### ISSUE THREAD

**Issue by TomokazuUehara** [s10a137g/todo-app#6]
https://github.com/s10a137g/todo-app/blob/main/app/model/category/Category.scala#L34

`case object RED     extends Color(code = 1, name = " RED ")`

で、nameの前後のスペースが気になりました。
なにのためか次第ですが、HTML上のスペースの意味だとすると、
CSSで対応するのが正と思いましたのでコメントまで。

**Comment by s10a137g** [comment]
不要なスペースでした。
修正しました。
