### ISSUE TITLE
RedirectのURLの書き方

### ISSUE THREAD

**Issue by TomokazuUehara** [s10a137g/todo-app#7]
https://github.com/s10a137g/todo-app/blob/main/app/controllers/category/CategoryController.scala#L126

でURLを直接書くのを止めたいですね。

`Redirect("/categories/list")`
　↓
`Redirect(routes.category.CategoryController.list)`

みたいな感じだったかと。。。

**Comment by s10a137g** [comment]
修正しました。

**Comment by TomokazuUehara** [comment]
確認しました！
