### ISSUE TITLE
お時間あったらチャレンジしてほしいお題：カテゴリ削除時の要件

### ISSUE THREAD

**Issue by TomokazuUehara** [s10a137g/todo-app#8]
https://github.com/s10a137g/todo-app/blob/main/app/controllers/category/CategoryController.scala#L189

https://nextbeat-external.atlassian.net/wiki/spaces/DEVNEWEDU/pages/1267269682/4-2-2

Category削除時にそのCategoryに該当するTodoのデータも更新する
Categoryが削除された時に、該当しているTodoを削除するか、
”どのカテゴリにも紐づいていない” というデータになるようTodoを更新する

この要件を実装するところで、Todoが複数あるような場合にどのように対応するのか？
の部分の実装をしていただけると良さそう。

**Comment by s10a137g** [comment]
修正しました、が削除する方で修正してしまいました。。。
一応Todo複数ある場合でも対応しています。

**Comment by TomokazuUehara** [comment]
個別で、もう片方のバージョンへの対応のサンプルコードをおくりますね。
